import { AppProps } from 'next/dist/shared/lib/router/router';
import Head from 'next/head';
import { Provider } from 'react-redux';

import { store } from '../src/redux/store';

import '../styles/globals.scss';

const MyApp = ({ Component, pageProps }: AppProps): JSX.Element => {
	return (
		<Provider store={store}>
			<div>
				<Head>
					<title>Musicfy</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<Component {...pageProps} />
			</div>
		</Provider>
	);
};

export default MyApp;
